// src/react/button.tsx
"use client";
import { useState } from "react";

const Button = () => {
  const [count, setCount] = useState(0);
  return (
    <button
      onClick={() => {
        console.log("react", count);
        setCount((prev) => prev + 1);
      }}
    >
      React {count}
    </button>
  );
};
export default Button;

// src/solid/button.tsx
import { createSignal } from "solid-js";

const Button = () => {
  const [count, setCount] = createSignal(0);
  return (
    <button
      onClick={() => {
        console.log("solid", count());
        setCount((prev) => prev + 1);
      }}
    >
      Solid {count()}
    </button>
  );
};
export default Button;
